### ISSUE TITLE
InstallReferrerClientImpl.java:133 // NoClassDefFoundError

### ISSUE THREAD

**Issue by toby78** [adjust/android_sdk#402]
This is happening on SDK29 on a physical device:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/aidl/BaseStub;
        at com.android.installreferrer.api.InstallReferrerClientImpl.startConnection(InstallReferrerClientImpl.java:133)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.adjust.sdk.Reflection.invokeMethod(Reflection.java:123)
```

**Comment by uerceg** [comment]
Hi @toby78 

Is this something which is crashing you app or are you simply noticing it in LogCat logs when running our SDK?

**Comment by calvarez-ov** [comment]
It crashes our app.

**Comment by calvarez-ov** [comment]
It happens with `implementation "com.android.installreferrer:installreferrer:1.1"`

It doesn't happen with `implementation "com.android.installreferrer:installreferrer:1.0"`

**Comment by uerceg** [comment]
Oh, so it happens with new version of Google library. Thanks for reporting. We will take a look. And in the meantime, feel free to use 1.0, it makes absolutely no difference for purpose we need the library for.

**Comment by calvarez-ov** [comment]
For info, here's a bit more stacktrace for context:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/aidl/BaseStub;
       at com.android.installreferrer.api.InstallReferrerClientImpl.startConnection(InstallReferrerClientImpl.java:133)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.adjust.sdk.Reflection.invokeMethod(Reflection.java:123)
       at com.adjust.sdk.Reflection.invokeInstanceMethod(Reflection.java:112)
       at com.adjust.sdk.InstallReferrer.startConnection(InstallReferrer.java:239)
       at com.adjust.sdk.InstallReferrer.startConnection(InstallReferrer.java:163)
       at com.adjust.sdk.ActivityHandler.processSessionI(ActivityHandler.java:955)
       at com.adjust.sdk.ActivityHandler.startI(ActivityHandler.java:876)
       at com.adjust.sdk.ActivityHandler.access$500(ActivityHandler.java:39)
       at com.adjust.sdk.ActivityHandler$2.run(ActivityHandler.java:309)
       at com.adjust.sdk.scheduler.SingleThreadCachedScheduler.tryExecuteRunnable(SingleThreadCachedScheduler.java:112)
       at com.adjust.sdk.scheduler.SingleThreadCachedScheduler.access$000(SingleThreadCachedScheduler.java:12)
       at com.adjust.sdk.scheduler.SingleThreadCachedScheduler$3.run(SingleThreadCachedScheduler.java:83)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.aidl.BaseStub" on path: DexPathList[[zip file "/data/app/com.myapp-9AeLRfFHId2pKHYHH9hZTA==/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp-9AeLRfFHId2pKHYHH9hZTA==/lib/x86, /data/app/com.myapp-9AeLRfFHId2pKHYHH9hZTA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by uerceg** [comment]
Awesome, thank you for this info. SDK will definitely need an update to support this Google's "under the radar" release of version 1.1 of the install referrer library. However, we still need to check what needs to be done and estimate the effort.

But like said, and as our README states - regardless of existence of this new install referrer library version, just stick with suggested version 1.0 and things should work just fine.

**Comment by toby78** [comment]
Ok, thanks. As long as no other lib requires 1.1 we can downgrade for now

**Comment by uerceg** [comment]
I highly doubt any of the libraries should drag dependency to version 1.1, although not impossible, of course (if they're adding dependencies with `+` mark in Gradle instead of stating actual version). But in this case, those libraries would notice this for sure.

Here's a bit more background on the issue FYI. Purpose of this library is to talk to Play Service app, obtain and return information about install referrer information for given user (origin of install). We obviously need it for attribution purposes. Since we don't want to drag direct dependency to this library, in our current SDK v4 code we went with reflection approach to obtain this information and initially we doubted that maybe some API changed causing reflection approach to fail. But after checks we did, we didn't notice any API change. Simply the moment in which connection with library is supposed to be established works with 1.0 and with 1.1 it throws exception (which can't even be caught with try-catch block; even if it could be caught, still doesn't change the fact that library seems to be completely useless now for purpose it's built for). This is the reason you encountered this issue. And this is why I'm saying that I (with current knowledge about the issue) doubt that any library would start to depend on 1.1 since it doesn't seem that it works well.

Even if one uses direct API referencing approach instead of reflection, absolutely same issue happens. So looks pretty weird. We also didn't manage to find any official release notes about this version and even official Google documentation about install referrer states that 1.0 should be added as dependency. We have decompiled library and noticed some interesting changes under the hood in code, but not to spam it in here - TLDR we'll try to reach out to Google and try to see what is happening.

Will keep you posted in here.

Cheers

**Comment by uerceg** [comment]
Update on this one. Google identified the issue and will probably come up with new version of library which addresses the issue in next few days. Will keep you posted.

Cheers

**Comment by toby78** [comment]
Thanks for the quick reponse!

**Comment by uerceg** [comment]
@toby78 @calvarez-ov 

Okay, seems like this issue should now be resolved on Google side. Please give version 1.1 another shot and in case you already have it cached from previous import, add it with

```gradle
implementation('com.android.installreferrer:installreferrer:1.1') { changing .= true}
```

Let us know if crash is not happening anymore and if you see that Adjust SDK is picking up install referrer information and sending it via `sdk_click` package (you can check this out when running SDK in sandbox mode with verbose log level turned on).

Cheers

**Comment by calvarez-ov** [comment]
Two questions:
1) What is the issue in the google tracker? I only found [this one](https://issuetracker.google.com/issues/145557612) but it isn't marked as resolved
2) Did google really release a fix with the same version number 1.1? This means no repeatable builds, which is not a good practice.

**Comment by uerceg** [comment]
Hi @calvarez-ov 

1. We reached out to their development team directly since it seemed pretty urgent, so we didn't open any issue in their issue tracker system. But the one you shared indeed does appear to be the one.
2. From what I understood, yes, it's actually under same version number and fully agree with you with the 2nd sentence.

**Comment by uerceg** [comment]
I guess there's nothing much left on our side to do about this issue, so will close it. In case any other issues regarding this topic pop up, feel free to reopen it or simply continue discussion in here.

Cheers and thanks for reporting!

**Comment by vakhileshwar** [comment]
I am facing issue after updating Android studio to 4.0

 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/finsky/externalreferrer/IGetInstallReferrerService$Stub;
        at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:3)

**Comment by tmtrademarked** [comment]
I suspect this issue may be popping up again because of the upgrade to version 2.0 of the install referrer library: https://developer.android.com/google/play/installreferrer/release-notes

I'm seeing this locally when I upgrade to 2.0 while using the Adjust SDK 4.22.0. Any chance an update is on the radar?

**Comment by uerceg** [comment]
Hey guys,

Thanks for reporting. We will be checking latest release of install referrer library and check what needs to be done on SDK side to make it work. For now if you can stick with version suggested to be integrated in README, would be awesome. Update for it will be made as soon as we can, will keep you posted.

Cheers
